<?php // Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'test_tf_rw_testlink');
define('DB_PASS', 'LqXu2FQH9pGMyJZPE6Bx7z');
define('DB_HOST', 'strapi-test-master.c29xaypvdafj.ap-south-1.rds.amazonaws.com');
define('DB_NAME', 'testlink');
?>