version: '3.1'

services:
  testlink:
    image: ${IMAGE_NAME}
    ports:
      - "7777:8080"
      - "443:443"
    depends_on:
      - mysql_testlink
    volumes:
      - ${VOLUME_DIR_TESTLINK}/gui/templates_c:/var/www/html/gui/templates_c
      - ${VOLUME_DIR_TESTLINK}/logs:/var/testlink/logs
      - ${VOLUME_DIR_TESTLINK}/upload_area:/var/www/html/upload_area
    environment:
      - IMAGE_NAME=${IMAGE_NAME}
      - VOLUME_DIR_TESTLINK=${VOLUME_DIR_TESTLINK}

  mysql_testlink:
    image: mysql/mysql-server:8.0.23
    ports:
      - 3301:3306
    # volumes:
    #  - ${VOLUME_DIR_MYSQL}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - VOLUME_DIR_MYSQL=${VOLUME_DIR_MYSQL}