<?php // Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlinkuser');
define('DB_PASS', 'testlink@123');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
?>